name = "TrenberthDiagram"
uuid = "a3bfdfcc-9561-43d2-ab0f-6df68171d2b0"
authors = ["Hannah-Jane Wood", "Lucy Harlow", "Ofer Cohen"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
